### ISSUE TITLE
Plays a different song than what's displayed

### ISSUE THREAD

**Issue by ruvaldak** [kienvtqhi/melocloud-issue-tracker#1]
Plays a different song than what's displayed, but only when I listen to the previous all the way through. If I skip to the next song it doesn't do so. It can be fixed by skipping to the next song then going back.

**Comment by kienvtqhi** [comment]
Hello Ruvaldak,

The bug is fixed in 1.3.2-Beta-1. The beta version is ready to download. You can join us on google plus community and become a tester. 

Thanks
John

**Comment by kienvtqhi** [comment]
Can you help me to confirm about the bug in the beta version? is it fixed on your device?

**Comment by ruvaldak** [comment]
Yeah, its fixed not sure a picture would do any good, but now the app isn't giving me false info as to what's playing
