### ISSUE TITLE
Easier song list navigsation

### ISSUE THREAD

**Issue by ruvaldak** [kienvtqhi/melocloud-issue-tracker#14]
I'm kind not digging having to scroll through the list of songs I got, it'd be cool if there was a bar on the right we could grab and it pop up a little letter indicator, helping us find songs based alphabetically easier. Kinda like nova launchers list feature (attached example)
![screenshot_2015-11-19-21-27-55](https://cloud.githubusercontent.com/assets/15901769/11291358/d02c0704-8f04-11e5-935b-a76a1fffd44e.png)

**Comment by kienvtqhi** [comment]
I got your idea. I have planned to do that but it is lower priority for now. We will add it to the app after we released the 1.3.2 to Google Store.

**Comment by ruvaldak** [comment]
Cool dude. Can't wait for 1.3.2, got some nice features probably! :)

**Comment by kienvtqhi** [comment]
Can you help me to confirm about the issue at #1?

**Comment by ruvaldak** [comment]
Yeah, its fixed not sure a picture would do any good, but now the app isn't giving me false info as to what's playing
