### ISSUE TITLE
Some texts and icons remain white and are barely visible, when using light themes.

### ISSUE THREAD

**Issue by jahirfiquitiva** [kienvtqhi/melocloud-issue-tracker#2]
![1447879310417](https://cloud.githubusercontent.com/assets/10360816/11255561/f1f2a492-8e14-11e5-82eb-e48484504dde.jpg)
![1447879350044](https://cloud.githubusercontent.com/assets/10360816/11255560/f1f02424-8e14-11e5-9027-359a9eda47a4.jpg)
![1447879318514](https://cloud.githubusercontent.com/assets/10360816/11255562/f1f37dae-8e14-11e5-8642-092049eb0b2e.jpg)

**Comment by jahirfiquitiva** [comment]
Another screenshot. Check all toolbars texts in all app sections too.

![1447884409092](https://cloud.githubusercontent.com/assets/10360816/11255939/0cf4ee24-8e17-11e5-86bc-bc144d1caf9e.jpg)

**Comment by kienvtqhi** [comment]
It looks like you chose grey light as the primary color? The highlighted state for text on sidebar menu is primary color. It is not a bug.

**Comment by jahirfiquitiva** [comment]
Sidebar menu is called Navigation Drawer.
And ok, it doesn't look so bad there.
But please fix the icons and texts in the rest of screenshots.

**Comment by kienvtqhi** [comment]
I known it called Navigation Drawer. But i am not sure about you, so i called sidebar menu to make sure anyone can understand what i am talking about :)

About the icons and texts in the toolbar, tab bar and playing bar. I will add more an option to the setting page to use dark action bar. When user have chosen to use the dark action bar, it will effect to the toolbar, tabbar and playingbar. 

Specifically, the icons on toolbar+ tabbar and the text color on playing bar will be change to grey. It is easier for user to customize the app.

**Comment by jahirfiquitiva** [comment]
Oh, you can easily use dev terms with me. If you check my GitHub page, my website or my G+ profile, you will find/notice that I develop apps too and that I'm into design too.

Now, what I am looking for or what I am expecting to see in MeloCloud is something like Phonograph has when using light themes. I love how it looks.

![screenshot_2015-11-19-07-05-32](https://cloud.githubusercontent.com/assets/10360816/11270360/44a53674-8e8c-11e5-9a72-c67f0c183fe1.png)
