### ISSUE TITLE
When songs have no album art seekbar and play/pause button have no color

### ISSUE THREAD

**Issue by jahirfiquitiva** [kienvtqhi/melocloud-issue-tracker#3]
I think the seekbar and play/pause button should be coloured with the user selected accent color.

Also, I would like you to add a little gradient (like you did in toolbar) right above the seekbar (where number 1 is), because sometimes it gets (kinda) mixed with the album art, and sometimes is a bit hard to see.

![screenshot_2015-11-18-15-40-16](https://cloud.githubusercontent.com/assets/10360816/11255683/9308b5d8-8e15-11e5-950a-2b6017ee8a6f.png)

**Comment by kienvtqhi** [comment]
The color of seekbar and play button will be picked from palette which generated from album artwork.If the song have no album artwork then the color of seekbar and play button will be the primary color. In the screenshot, you have chosen grey light as the primary color.

**Comment by jahirfiquitiva** [comment]
It should be the accent color instead of the primary one. That's what it is supposed to be for.
