### ISSUE TITLE
Player doesn't broadcast what's being played

### ISSUE THREAD

**Issue by jahirfiquitiva** [kienvtqhi/melocloud-issue-tracker#4]
Some other players have something (I'm not really sure of its name), that makes other apps be able to know what the app is playing (song, artist, album, song progress, etc).

I think is called broadcast or something.

It is used by [Musixmatch](https://play.google.com/store/apps/details?id=com.musixmatch.android.lyrify) (for example) to be able to know what song is being played, and show the right lyrics for the song, and sync them with the progress of the same.

Apps I know that include it: [Shuttle](https://play.google.com/store/apps/details?id=another.music.player), [BlackPlayer Ex](https://play.google.com/store/apps/details?id=com.kodarkooperativet.blackplayerex), [Spotify](https://play.google.com/store/apps/details?id=com.spotify.music).

**Comment by kienvtqhi** [comment]
You mean the playing song doesn't display properly?

**Comment by jahirfiquitiva** [comment]
No, I mean apps like Musixmatch don't know what is being played and lyrics won't show neither sync.
