### ISSUE TITLE
When opening the app from the notification the part below the artwork get coloured and anything is visible

### ISSUE THREAD

**Issue by jahirfiquitiva** [kienvtqhi/melocloud-issue-tracker#5]
This is what happens after pressing the notification to open the app. Happens with all songs.

![screenshot_2015-11-18-17-07-36](https://cloud.githubusercontent.com/assets/10360816/11255964/3a603062-8e17-11e5-9c27-a5f41227dc66.png)

**Comment by pranjalshah9814** [comment]
I'm facing a similar problem except for the fact that even the queue info at the bottom is getting covered and that this problem arises even when I enter the now playing screen from within the app itself
