### ISSUE TITLE
Sleep timer dialog has a bug.

### ISSUE THREAD

**Issue by jahirfiquitiva** [kienvtqhi/melocloud-issue-tracker#6]
When time is 0, it shows a complete circle.

![screenshot_2015-11-18-17-11-30](https://cloud.githubusercontent.com/assets/10360816/11256014/9c9a1950-8e17-11e5-9668-438c7adeb5d9.png)

**Comment by kienvtqhi** [comment]
@jahirfiquitiva How can you set the timer to 0 min?

**Comment by jahirfiquitiva** [comment]
I obviously don't. But is a visual bug. It shouldn't look like that.

After pressing Sleep Timer option, what comes is thay dialog with 0 as current value.

It shouldn't look like this even if anyone will move it in a couple seconds.
